// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooManagmentSystem.Data;

#nullable disable

namespace ZooManagmentSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318174126_Raports")]
    partial class Raports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZooManagmentSystem.Models.AnimalHistoryModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Animalid")
                        .HasColumnType("int");

                    b.Property<int>("ConditionAdmission")
                        .HasColumnType("int");

                    b.Property<bool>("IsVacinated")
                        .HasColumnType("bit");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("Animalid");

                    b.ToTable("AnimalHistories");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.AnimalHistoryRaportModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Animalid")
                        .HasColumnType("int");

                    b.Property<int?>("Authorid")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Animalid");

                    b.HasIndex("Authorid");

                    b.ToTable("AnimalHistoryRaports");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.AnimalModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("DateOfArrival")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("EnclosureModelid")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("EnclosureModelid");

                    b.ToTable("Animals");

                    b.HasDiscriminator().HasValue("AnimalModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Supervisorid")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Supervisorid");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.EnclosureModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Enclosures");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.FeedingPlanRaportModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Authorid")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeAssignedid")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Authorid");

                    b.HasIndex("EmployeeAssignedid");

                    b.ToTable("FeedingPlanRaports");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.TaskModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Animalid")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedEmployeeid")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Enclosureid")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Animalid");

                    b.HasIndex("AssignedEmployeeid");

                    b.HasIndex("Enclosureid");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.BirdModel", b =>
                {
                    b.HasBaseType("ZooManagmentSystem.Models.AnimalModel");

                    b.Property<bool>("CanFly")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HatchedDate")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("BirdModel");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.MammalModel", b =>
                {
                    b.HasBaseType("ZooManagmentSystem.Models.AnimalModel");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("MammalModel");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.AnimalHistoryModel", b =>
                {
                    b.HasOne("ZooManagmentSystem.Models.AnimalModel", "Animal")
                        .WithMany()
                        .HasForeignKey("Animalid");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.AnimalHistoryRaportModel", b =>
                {
                    b.HasOne("ZooManagmentSystem.Models.AnimalModel", "Animal")
                        .WithMany()
                        .HasForeignKey("Animalid");

                    b.HasOne("ZooManagmentSystem.Models.Employee", "Author")
                        .WithMany()
                        .HasForeignKey("Authorid");

                    b.Navigation("Animal");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.AnimalModel", b =>
                {
                    b.HasOne("ZooManagmentSystem.Models.EnclosureModel", null)
                        .WithMany("animals")
                        .HasForeignKey("EnclosureModelid");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.Employee", b =>
                {
                    b.HasOne("ZooManagmentSystem.Models.Employee", "Supervisor")
                        .WithMany()
                        .HasForeignKey("Supervisorid");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.FeedingPlanRaportModel", b =>
                {
                    b.HasOne("ZooManagmentSystem.Models.Employee", "Author")
                        .WithMany()
                        .HasForeignKey("Authorid");

                    b.HasOne("ZooManagmentSystem.Models.Employee", "EmployeeAssigned")
                        .WithMany()
                        .HasForeignKey("EmployeeAssignedid");

                    b.Navigation("Author");

                    b.Navigation("EmployeeAssigned");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.TaskModel", b =>
                {
                    b.HasOne("ZooManagmentSystem.Models.AnimalModel", "Animal")
                        .WithMany()
                        .HasForeignKey("Animalid");

                    b.HasOne("ZooManagmentSystem.Models.Employee", "AssignedEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedEmployeeid");

                    b.HasOne("ZooManagmentSystem.Models.EnclosureModel", "Enclosure")
                        .WithMany()
                        .HasForeignKey("Enclosureid");

                    b.Navigation("Animal");

                    b.Navigation("AssignedEmployee");

                    b.Navigation("Enclosure");
                });

            modelBuilder.Entity("ZooManagmentSystem.Models.EnclosureModel", b =>
                {
                    b.Navigation("animals");
                });
#pragma warning restore 612, 618
        }
    }
}
